GOLF/Assets/_Project/Scripts/Input/InputManager.cs
GOLF/Assets/_Project/Scripts/Player/BallController.cs

Modified InputManager and BallController scripts. Added an OnDestroy method so we can unsuscribe from the input event and also added one to the InputManager so it clears the previous instance of the player.

Fixed player movement bug

---

GOLF/Assets/_Project/Scenes/Credits.unity
GOLF/Assets/_Project/Scripts/UI/CreditsScroller.cs
GOLF/Assets/_Project/Scripts/UI/CreditsScroller.cs.meta
GOLF/ProjectSettings/ProjectSettings.asset

The credits scene was created, in addition to giving it its movement and keeping it on a loop
closes #11

Credit Screen

---

GOLF/Assets/_Project/Scripts/Game/GameManager.cs
GOLF/Assets/_Project/Scripts/Game/GameManager.cs.meta
GOLF/Assets/_Project/Scripts/Game/IGameSource.cs
GOLF/Assets/_Project/Scripts/Game/IGameSource.cs.meta

Created a very simple GameManager script and implemented two basic methods on its interface for the score (amount of strokes left)

GameManager creation and score addition

---

GOLF/Assets/_Project/Scenes/Tutorial.unity
GOLF/Assets/_Project/Scripts/Input/IInputSource.cs
GOLF/Assets/_Project/Scripts/Input/InputManager.cs
GOLF/Assets/_Project/Scripts/Levels/Tutorial/MainMenuBack.cs
GOLF/Assets/_Project/Scripts/Levels/Tutorial/MainMenuBack.cs.meta

Script where you can return to main menu from the hub
Close #40

Return to main menu from the hub

---

GOLF/Assets/_Project/Scripts/Save System/SaveSystem.cs

I remoed the method but not one of its calls.... sorry XD

[HOTFIX] Removed missing method call in Save system

---

GOLF/Assets/_Project/Scripts/Dialogue/DialogueManager.cs
GOLF/Assets/_Project/Scripts/Dialogue/DialogueTrigger.cs
GOLF/Assets/_Project/Scripts/Dialogue/IDialogueSource.cs
GOLF/Assets/_Project/Scripts/Game.meta
GOLF/Assets/_Project/Scripts/Input/IInputSource.cs
GOLF/Assets/_Project/Scripts/Input/InputManager.cs

Fixed the bug of the player's movement while in the dialog window.

Moving while dialogue fixed

---

GOLF/Assets/_Project/Art/Assets/Ball/scratcher.png
GOLF/Assets/_Project/Art/Assets/Ball/scratcher.png.meta
GOLF/Assets/_Project/Scenes/Tutorial.unity

Change the main menu trigger sprite on the Hub scene
Close #48

Scratcher sprites added

---

GOLF/Assets/_Project/Art/Assets/Hole.meta
GOLF/Assets/_Project/Art/Assets/Hole/hole-sprite.png
GOLF/Assets/_Project/Art/Assets/Hole/hole-sprite.png.meta

Created and added hole sprite here's how it looks in the scene.
Close #65

Hole sprite addition

---

GOLF/Assets/_Project/Scripts/Dialogue/DialogueManager.cs

Fixed bug. Here's a [video](https://youtu.be/-iOWzWN45t8) showing how it works now.
Close #73

Dialogue bug fix

---

GOLF/Assets/_Project/Art/UI/Slider.meta
GOLF/Assets/_Project/Art/UI/Slider/sliders.png
GOLF/Assets/_Project/Art/UI/Slider/sliders.png.meta
GOLF/Assets/_Project/Prefabs/Player/Ball.prefab

Added art to the force slider. This is how it looks.
Close #59 
https://github.com/user-attachments/assets/8a30b3ce-f15b-456e-9e4c-1cc04ca0cc2e

Force bar sprite

---

GOLF/Assets/_Project/Prefabs/Managers/GameManager.prefab
GOLF/Assets/_Project/Prefabs/Managers/LevelManager.prefab
GOLF/Assets/_Project/Prefabs/Managers/MainGameCamera.prefab
GOLF/Assets/_Project/Prefabs/Managers/MainGameCamera.prefab.meta
GOLF/Assets/_Project/Prefabs/Managers/UIManager.prefab
GOLF/Assets/_Project/Scenes/FirstLevel.unity
GOLF/Assets/_Project/Scenes/Tutorial.unity
GOLF/Assets/_Project/Scripts/Camera/CameraInputManager.cs
GOLF/Assets/_Project/Scripts/Levels/LevelManager.cs
GOLF/Assets/_Project/Scripts/Levels/Tutorial/LevelSelector.cs
GOLF/Assets/_Project/Scripts/Player/BallController.cs
GOLF/Assets/_Project/Scripts/UI/UIManager.cs
GOLF/Assets/_Utilities/Singleton/Singleton.cs

Closes #84 
The big error was caused but a bad singleton management, while doing that I regrouped some systems on prefabs so all of them are correctly encapsulated plus some other thingies.

Fixed game flow error when falling in water

---

GOLF/Assets/_Project/Prefabs/Player/Player.prefab
GOLF/Assets/_Project/Prefabs/Player/Player.prefab.meta
GOLF/Assets/_Project/Scenes/FirstLevel.unity
GOLF/Assets/_Project/Scenes/Tutorial.unity
GOLF/Assets/_Project/Scripts/Player/HUD/ForceSliderPosition.cs
GOLF/Assets/_Project/Scripts/Player/HUD/ForceSliderPosition.cs.meta

Here's how the force bar slider behaves now.  Close #71 
https://github.com/user-attachments/assets/f1541818-c66c-455c-8fd8-af0a642bee1f

Force bar fix

---

GOLF/Assets/_Project/Art/UI/Camera.meta
GOLF/Assets/_Project/Art/UI/Camera/ArrowCamera.png
GOLF/Assets/_Project/Art/UI/Camera/ArrowCamera.png.meta
GOLF/Assets/_Project/Prefabs/Managers/MainGameCamera.prefab
GOLF/Assets/_Project/Scenes/FirstLevel.unity
GOLF/Assets/_Project/ScriptableObjects/CameraThresholds/Level 1.asset
GOLF/Assets/_Project/Scripts/Camera/CameraInputConfigurations.cs
GOLF/Assets/_Project/Scripts/Camera/CameraInputManager.cs
GOLF/Assets/_Project/Scripts/Input/IInputSource.cs
GOLF/Assets/_Project/Scripts/Input/InputManager.cs

Change in the size and function in the camera
https://github.com/user-attachments/assets/2c0f5220-bd2e-48cb-be1d-5f8ddcca0a53
Close #90

Changes in camera system

---

GOLF/Assets/_Project/Art/Assets/Water.meta
GOLF/Assets/_Project/Art/Assets/Water/Water.asset
GOLF/Assets/_Project/Art/Assets/Water/Water.asset.meta
GOLF/Assets/_Project/Art/Assets/Water/water.png
GOLF/Assets/_Project/Art/Assets/Water/water.png.meta
GOLF/Assets/_Project/Art/Tilemaps/Water.prefab
GOLF/Assets/_Project/Art/Tilemaps/Water.prefab.meta

https://github.com/user-attachments/assets/be38d235-16a3-4e29-868b-0a1177177653
Close #57

Water sprite

---

GOLF/Assets/_Project/Art/UI/Direction Linerenderer.meta
GOLF/Assets/_Project/Art/UI/Direction Linerenderer/Yellow circle.png
GOLF/Assets/_Project/Art/UI/Direction Linerenderer/Yellow circle.png.meta
GOLF/Assets/_Project/Materials/M_Linerenderer.mat
GOLF/Assets/_Project/Materials/M_Linerenderer.mat.meta
GOLF/Assets/_Project/Prefabs/Player/Player.prefab
GOLF/Assets/_Project/Scenes/Tutorial.unity

Direction sprite added

---

GOLF/Assets/_Project/Art/Assets/Materials.meta
GOLF/Assets/_Project/Art/Assets/Materials/FlagSkull.mat
GOLF/Assets/_Project/Art/Assets/Materials/FlagSkull.mat.meta
GOLF/Assets/_Project/Scenes/TurotialLevel.unity
GOLF/Assets/_Project/Scenes/TurotialLevel.unity.meta

Design Document for the level: https://docs.google.com/document/d/1Rnlom1bSowv7E12wkz5ZqaM26YuKJ4LbqxP1Uk1B1UM/edit?usp=sharing
Close #82

New tutorial level was build

---

GOLF/Assets/_Project/Prefabs/Managers/LevelManager.prefab
GOLF/Assets/_Project/Scripts/Levels/LevelManager.cs

https://github.com/user-attachments/assets/15a6d41d-ddda-45d7-b033-100966b9d65f
Close #93

Loading bar added

---

GOLF/Assets/_Project/Art/UI/Buttons/GUI.png.meta
GOLF/Assets/_Project/Prefabs/Managers/GameStateManager.prefab
GOLF/Assets/_Project/Prefabs/Managers/GameStateManager.prefab.meta
GOLF/Assets/_Project/Prefabs/Managers/UIManager.prefab
GOLF/Assets/_Project/Scenes/Fireball Cave.unity
GOLF/Assets/_Project/Scenes/TESTING.unity
GOLF/Assets/_Project/Scenes/Test Eric.unity
GOLF/Assets/_Project/Scripts/Game/GameStateManager.cs
GOLF/Assets/_Project/Scripts/Game/GameStateManager.cs.meta
GOLF/Assets/_Project/Scripts/Game/IGameStateSource.cs
GOLF/Assets/_Project/Scripts/Game/IGameStateSource.cs.meta
GOLF/Assets/_Project/Scripts/Input/IInputSource.cs
GOLF/Assets/_Project/Scripts/Input/InputManager.cs
GOLF/Assets/_Project/Scripts/Player/BallController.cs
GOLF/Assets/_Project/Scripts/UI/IUISource.cs
GOLF/Assets/_Project/Scripts/UI/UIManager.cs
GOLF/ProjectSettings/ProjectSettings.asset

First commit of the task, 
The pause is activated when we press the "Escape" key, it saves the velocity and the angle of the ball and disables the input while the menu is on the screen. 
Clip of the pause working: https://drive.google.com/file/d/1GxX4sSsGq7Ba-b4Bafp7k_HtZTS14tCY/view?usp=sharing 
Close #85

Pause mode and Pause menu

---

GOLF/Assets/_Project/Art/Animations/BloodFlagAnimation.anim
GOLF/Assets/_Project/Art/Animations/BloodFlagAnimation.anim.meta
GOLF/Assets/_Project/Art/Animations/Flag 1.controller
GOLF/Assets/_Project/Art/Animations/Flag 1.controller.meta
GOLF/Assets/_Project/Art/Animations/Flag 2.controller
GOLF/Assets/_Project/Art/Animations/Flag 2.controller.meta
GOLF/Assets/_Project/Art/Animations/FlagAnimation.anim
GOLF/Assets/_Project/Art/Animations/FlagAnimation.anim.meta
GOLF/Assets/_Project/Art/Animations/FrozenFlagAnimation.anim
GOLF/Assets/_Project/Art/Animations/FrozenFlagAnimation.anim.meta
GOLF/Assets/_Project/Art/Assets/Flag/Biberon.png
GOLF/Assets/_Project/Art/Assets/Flag/Biberon.png.meta
GOLF/Assets/_Project/Art/Assets/Flag/BloodFlag.prefab
GOLF/Assets/_Project/Art/Assets/Flag/BloodFlag.prefab.meta
GOLF/Assets/_Project/Art/Assets/Flag/BloodFlagAnimation.png
GOLF/Assets/_Project/Art/Assets/Flag/BloodFlagAnimation.png.meta
GOLF/Assets/_Project/Art/Assets/Flag/CatSkeleton.png
GOLF/Assets/_Project/Art/Assets/Flag/CatSkeleton.png.meta
GOLF/Assets/_Project/Art/Assets/Flag/DemonCat.png
GOLF/Assets/_Project/Art/Assets/Flag/DemonCat.png.meta
GOLF/Assets/_Project/Art/Assets/Flag/FlagAnimation.png
GOLF/Assets/_Project/Art/Assets/Flag/FrozenFlag.prefab
GOLF/Assets/_Project/Art/Assets/Flag/FrozenFlag.prefab.meta
GOLF/Assets/_Project/Art/Assets/Flag/FrozenFlagAnimation.png
GOLF/Assets/_Project/Art/Assets/Flag/FrozenFlagAnimation.png.meta
GOLF/Assets/_Project/Art/Assets/Flag/SnowCat.png
GOLF/Assets/_Project/Art/Assets/Flag/SnowCat.png.meta
GOLF/Assets/_Project/Scenes/TESTING.unity

New animations and sprites for decoration of the different levels.
Now we have 3 different flags, the frozen flag, blood flag and the normal one. 
We have different companions for the holes we have the demon cat and the skeleton for the crimson level, we have a fedding bottle for the tutorial and a Snowman with cat ears.
https://github.com/user-attachments/assets/d3da485b-3f0c-4b5e-8533-53dcf2197889

New decorative sprites for holes

---

GOLF/Assets/_Project/Prefabs/DialoguesPrefabs/DialogueBox Cinematics.prefab
GOLF/Assets/_Project/Prefabs/DialoguesPrefabs/DialogueBox Cinematics.prefab.meta
GOLF/Assets/_Project/Scenes/FireballCave.unity
GOLF/ProjectSettings/EditorBuildSettings.asset

New UI added to the Dialogues box
https://github.com/user-attachments/assets/a4b6dc32-082d-4ad2-9d51-c8629215bebd
Close #123

Revamp dialogues UI

---

GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart.meta
GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart/Nintendo_Buttons.png
GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart/Nintendo_Buttons.png.meta
GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart/Nintendo_Cross.png
GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart/Nintendo_Cross.png.meta
GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart/Playstation_Buttons.png
GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart/Playstation_Buttons.png.meta
GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart/Playstation_Cross.png
GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart/Playstation_Cross.png.meta
GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart/Xbox_Buttons.png
GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart/Xbox_Buttons.png.meta
GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart/Xbox_Cross.png
GOLF/Assets/_Project/Art/UI/Buttons/Controller Buttons 16x16 Pixelart/Xbox_Cross.png.meta
GOLF/Assets/_Project/Art/UI/Buttons/Keyboard UI asset pack.meta
GOLF/Assets/_Project/Art/UI/Buttons/Keyboard UI asset pack/Keyboard_Buttons.png
GOLF/Assets/_Project/Art/UI/Buttons/Keyboard UI asset pack/Keyboard_Buttons.png.meta
GOLF/Assets/_Project/Prefabs/UI.meta
GOLF/Assets/_Project/Prefabs/UI/InputComponentCanvas.prefab
GOLF/Assets/_Project/Prefabs/UI/InputComponentCanvas.prefab.meta
GOLF/Assets/_Project/Scripts/Input/IInputSource.cs
GOLF/Assets/_Project/Scripts/Input/InputManager.cs
GOLF/Assets/_Project/Scripts/UI/UIInputComponent.cs
GOLF/Assets/_Project/Scripts/UI/UIInputComponent.cs.meta

Created a script which changes an image depending on which type of controller (keyboard or xbox) is being used. Modified the InputManager and its interface to add the respective functions and events. Here's a video showing how it works. Added a debug message only for demonstration purposes but removed it from the code.
https://github.com/user-attachments/assets/e7ed588d-0494-4394-9ecd-c24cf8936c0b
Close #129

UI component change

---

GOLF/Assets/_Project/Prefabs/DialoguesPrefabs/DialogueBox Gameplay.prefab
GOLF/Assets/_Project/Scenes/FireballCave.unity
GOLF/Assets/_Project/Scenes/Level1.unity
GOLF/Assets/_Project/ScriptableObjects/Dialogues/FireCave.asset
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers.meta
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Hard path.asset
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Hard path.asset.meta
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Protagonist comment.asset
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Protagonist comment.asset.meta
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Protagonist commentary.asset
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Protagonist commentary.asset.meta
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Taunt 1.asset
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Taunt 1.asset.meta
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Taunt 2.asset
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Taunt 2.asset.meta
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Taunt 3.asset
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Taunt 3.asset.meta
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Taunt 4.asset
GOLF/Assets/_Project/ScriptableObjects/Dialogues/Level 1 triggers/Taunt 4.asset.meta
GOLF/Assets/_Project/Scripts/Dialogue/Dialogue.cs
GOLF/Assets/_Project/Scripts/Dialogue/DialogueGameplayTrigger.cs
GOLF/Assets/_Project/Scripts/Dialogue/DialogueGameplayTrigger.cs.meta
GOLF/Assets/_Project/Scripts/Dialogue/DialogueManager.cs
GOLF/Assets/_Project/Scripts/Dialogue/DialogueTrigger.cs
GOLF/Assets/_Project/Scripts/Dialogue/IDialogueSource.cs

https://github.com/user-attachments/assets/59db8184-f9d5-4e7b-a0aa-cfd0034f3501
Background dialogues added to specific spots in the level. An animation was added as well.
These was the dialogues added
Close #67

Background dialogues

---

GOLF/Assets/_Project/Scenes/FireballCave.unity
GOLF/Assets/_Project/Scenes/Level2.unity
GOLF/Assets/_Project/Scenes/LevelSelector.unity
GOLF/Assets/_Project/Scenes/Tutorial.unity

Added the missing EventSystem object to the scene which is why the pause menu was unable to select the "Play" button.
https://github.com/user-attachments/assets/15f0ba76-cea9-4019-b552-de62a910d3ab
Close #168

LevelSelector pause fix

---

GOLF/Assets/_Project/Art/UI/Camera/Empty icon.png
GOLF/Assets/_Project/Art/UI/Camera/Empty icon.png.meta
GOLF/Assets/_Project/Prefabs/Managers/MainGameCamera.prefab
GOLF/Assets/_Project/Scenes/Level1.unity
GOLF/Assets/_Project/Scenes/Tutorial.unity
GOLF/Assets/_Project/Scripts/Camera/CameraInputManager.cs

Following the feedback we received on Friday, the camera arrows now hide when the camera reaches its threshold. We've also added the controls below the screen.
https://github.com/user-attachments/assets/7f3e3949-e89c-4fa1-a9e9-d69b9d17a9af
Close #155
Close #160

Camera UI feedback

---

GOLF/Assets/_Project/Art/UI/Buttons/Keyboard UI asset pack/delete-key.png
GOLF/Assets/_Project/Art/UI/Buttons/Keyboard UI asset pack/delete-key.png.meta
GOLF/Assets/_Project/Art/UI/Buttons/Keyboard UI asset pack/esc-key.png
GOLF/Assets/_Project/Art/UI/Buttons/Keyboard UI asset pack/esc-key.png.meta
GOLF/Assets/_Project/Scenes/MainMenu.unity

Now the Delete text has its backspace key sprite and the Back text has the ESC key sprite
Close #153

Save slots sprites reorder

---

GOLF/Assets/_Project/Scenes/Level1.unity
GOLF/Assets/_Project/Scenes/Level2.unity
GOLF/Assets/_Project/Scenes/LevelSelector.unity
GOLF/Assets/_Project/Scripts/Player/BallController.cs

Player movement has been blocked while in the hole, and the strength and direction handlers no longer appear.
The scenes have been modified; all holes are tagged as "Hole" so they work correctly.
In the video, you can see how when the ball is scored in the hole, while the FadeOut animation is playing, the strength and direction handlers no longer appear.
https://github.com/user-attachments/assets/52eb17da-e424-4fa3-87b8-03a79aef6903
close #156

Stopped moving while pole

---

GOLF/Assets/_Project/Art/Fonts/upheavtt SDF OUTLINE.asset
GOLF/Assets/_Project/Art/Fonts/upheavtt SDF OUTLINE.asset.meta
GOLF/Assets/_Project/Scenes/LevelSelector.unity

Text was created to indicate that the Scratcher is used to go to the main menu, and another font was also created with the outlined text.
Close #161

Text and Indicator for MainMenu

---

GOLF/Assets/_Project/Prefabs/Player/Player.prefab

The ball layer was fixed and tested in different scenes, going through all the locations to see where it was having issues. The only issue was the Fireball Cave, but it was resolved.
Close #158

Ball layer fixed

---

GOLF/Assets/_Project/Art/Animations/Ice.meta
GOLF/Assets/_Project/Art/Animations/Ice/idle.anim
GOLF/Assets/_Project/Art/Animations/Ice/idle.anim.meta
GOLF/Assets/_Project/Art/Animations/Ice/melt1.anim
GOLF/Assets/_Project/Art/Animations/Ice/melt1.anim.meta
GOLF/Assets/_Project/Art/Animations/Ice/melt2.anim
GOLF/Assets/_Project/Art/Animations/Ice/melt2.anim.meta
GOLF/Assets/_Project/Art/Animations/Ice/sprite_sheet_hielo.png
GOLF/Assets/_Project/Art/Animations/Ice/sprite_sheet_hielo.png.meta
GOLF/Assets/_Project/Art/Animations/Ice/sprite_sheet_hielo_0.controller
GOLF/Assets/_Project/Art/Animations/Ice/sprite_sheet_hielo_0.controller.meta
GOLF/Assets/_Project/Scenes/PowerUpsTest.unity
GOLF/Assets/_Project/Scripts/Camera/CameraZoomTrigger.cs
GOLF/Assets/_Project/Scripts/Camera/CameraZoomTrigger.cs.meta
GOLF/Assets/_Project/Scripts/Objects/Wall.cs

https://github.com/user-attachments/assets/31ec8db5-c90a-4b58-851c-b31edc74b437
Close #132

Fire power up effect

---

GOLF/Assets/_Project/Scripts/Audio/AudioManager.cs
GOLF/Assets/_Project/Scripts/Audio/IAudioSource.cs
GOLF/Assets/_Project/Scripts/Levels/EndLevelTrigger.cs

Removed some lines that were causing some problems with the way the audio sounds through the whole game.
https://github.com/user-attachments/assets/de6eca2b-55e3-4af2-ba3a-3f11812f8969
Close #190

AudioManager and settings fix

---

GOLF/Assets/_Project/Art/Animations/RustyFlag.controller
GOLF/Assets/_Project/Art/Animations/RustyFlag.controller.meta
GOLF/Assets/_Project/Art/Animations/RustyFlagAnimation.anim
GOLF/Assets/_Project/Art/Animations/RustyFlagAnimation.anim.meta
GOLF/Assets/_Project/Art/Assets/Flag/RustyFlag.png
GOLF/Assets/_Project/Art/Assets/Flag/RustyFlag.png.meta
GOLF/Assets/_Project/Art/Assets/Flag/RustyFlag.prefab
GOLF/Assets/_Project/Art/Assets/Flag/RustyFlag.prefab.meta
GOLF/Assets/_Project/Scenes/TESTING.unity

New animation and flag for level 3, I tried to make it look rusty and dirty. 
Close #201 
https://github.com/user-attachments/assets/53eb6f34-e623-43af-b226-3cbdeb733f9e

New flag for lvl 3 and animation

---

GOLF/Assets/_Project/Prefabs/Managers/MainGameCamera.prefab
GOLF/Assets/_Project/Scenes/FireballCave.unity
GOLF/Assets/_Project/Scenes/Level1.unity
GOLF/Assets/_Project/Scenes/Level2.unity
GOLF/Assets/_Project/Scripts/PowerUps/IPowerSource.cs
GOLF/Assets/_Project/Scripts/PowerUps/PowerUpSystem.cs
GOLF/Assets/_Project/Scripts/UI/UIIceInputComponent.cs
GOLF/Assets/_Project/Scripts/UI/UIIceInputComponent.cs.meta

Added a UI component to indicate when the ice power-up is available
https://github.com/user-attachments/assets/f1632142-608c-4cf1-8235-c4dfb9174969
Close #207

Ice power up GUI

---

GOLF/Assets/_Project/Prefabs/Managers/MainGameCamera.prefab
GOLF/Assets/_Project/Scenes/LevelSelector.unity
GOLF/Assets/_Project/ScriptableObjects/CameraThresholds/Hub.asset
GOLF/Assets/_Project/Scripts/Input/InputManager.cs

Correct the shoot icon and change the aim icon on keyboard controllers according by a feedback i received.
Now, the level selector scene will display the controls like the other scenes.
Closes #226
Closes #221

UI changes

---

GOLF/Assets/_Project/Scripts/Player/BallController.cs

Fixed an issue that caused a soft lock.

Ball controller hot fix

---

GOLF/Assets/_Project/Art/Assets/Ball/HeavyBall.png
GOLF/Assets/_Project/Art/Assets/Ball/HeavyBall.png.meta
GOLF/Assets/_Project/Scenes/Level3.unity
GOLF/Assets/_Project/ScriptableObjects/PowerUps/HeavyPowerUp.asset

The sprite for the heavy power up was created and implemented.
Close #246

heavy powerup sprite

---

GOLF/Assets/_Project/Art/Animations/Heavy.png
GOLF/Assets/_Project/Art/Animations/Heavy.png.meta
GOLF/Assets/_Project/Art/Animations/HeavyPowerUp.anim
GOLF/Assets/_Project/Art/Animations/HeavyPowerUp.anim.meta
GOLF/Assets/_Project/Art/Animations/HeavyPowerUp.controller
GOLF/Assets/_Project/Art/Animations/HeavyPowerUp.controller.meta
GOLF/Assets/_Project/Art/Animations/HeavyPowerUp.prefab
GOLF/Assets/_Project/Art/Animations/HeavyPowerUp.prefab.meta
GOLF/Assets/_Project/Scenes/HeavyShotCave.unity
GOLF/Assets/_Project/Scenes/Level3.unity

Created and implemented heavy Power up animation. 
Close #210 
https://github.com/user-attachments/assets/73bd988c-d75a-40a1-8b40-9b668de3a5a4

Animation for Heavy power up
